### ISSUE TITLE
Specific Environment Requirements

### ISSUE THREAD

**Issue by Eason51** [JanineCHEN/AAG-FP#1]
Hi, I have tried to config the environment, but it always seem to be some conflicts between the torch verison, the detectron2 version and the version of packages in requirement.txt. May I ask for the specific versions of packages you have used when you run the application?

**Comment by JanineCHEN** [comment]
Hi, sorry for the inconvenience, `torch==1.9.1+cu111` and `detectron2==0.6+cu111` were used for the project. 
The package version info has been updated in `readme` and `requirements.txt` accordingly.

**Comment by Eason51** [comment]
Thank you very much!

I first tried to install python3.7, torch1.9.1+cu111, and install the prebuilt detectron2 v0.6 following their given instruction, then when I run the code, it issues the following error:
`from detectron2 import _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory`, 

then I try to build detectron2 from source, but it issues the following error: 
`File "/ssddata2/yhubf/anaconda3/envs/floorplan2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension`

This looks like a pytorch compatibility problem. Then I try to reconfig the environment using python3.6, when using the prebuilt detectron2 v0.6 package, it issues the same libtorch_cuda_cu.so not found error. Then I also try to built it from source, but then building it requires a python>=3.7.

**Comment by Eason51** [comment]
The only way that I found to progress a little bit further is to use install torch and detectron2 at the same time using conda. But after I created the conda environment with python3.7, torch=1.9.1+cu111, detectron=0.6+cu111, torchvision=0.10.1+cu111，when I install requirement.txt, it issues one conflict.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
detectron2 0.6 requires black==21.4b2, which is not installed.
```

Then I manually add this package, then when I run the script, it issues the following error.
 
`RuntimeError: DGL requires PyTorch >= 1.12.0`

So I downgrade dgl to 0.9.0, as it is compatible with Pytorch 1.9.1，and the script seems to be working.

When the models are loaded, there seems to be some mismatching between the model definition and the keys stored in the checkpoint file:

```
CubiCasa5k Model for walls/doors/windows/rooms loaded.
An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions.
Traceback (most recent call last):
  File "/home/eason/anaconda3/envs/floorplan2/lib/python3.7/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys
    handler.log_event()
  File "/home/eason/anaconda3/envs/floorplan2/lib/python3.7/site-packages/iopath/common/event_logger.py", line 97, in log_event
    del self._evt
AttributeError: _evt
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
Detectron 2 Mask R-CNN for Wall/Door/Windows loaded.
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
Detectron 2 Mask R-CNN for Stairs loaded.
LOAD MODELS--- 17.49679183959961 seconds ---
```

Nevertheless, it continues to run. Until this point:

```
Mask R-CNN: Wall/Door/Window--- 40.28246235847473 seconds ---
Mask R-CNN: Stairs--- 41.20515322685242 seconds ---
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    G,G_n,G_m = graph_extractor(img_path, out_path)
  File "/home/eason/floorplan/AAG-FP/graph_extractor.py", line 618, in graph_extractor
    transform = aff,
  File "/home/eason/anaconda3/envs/floorplan2/lib/python3.7/site-packages/rasterio/env.py", line 387, in wrapper
    return f(*args, **kwds)
  File "/home/eason/anaconda3/envs/floorplan2/lib/python3.7/site-packages/rasterio/features.py", line 284, in rasterize
    for index, item in enumerate(shapes):
TypeError: 'MultiPolygon' object is not iterable
```

After a bit of search, I modified line 615 of file `graph_extractor.py`, changed `(MultiPolygon(rectangles),` to   `(MultiPolygon(rectangles).geoms), `, and it seems to work.

Likewise, for a similar error, I modified line 184 of file `methods.py`, changed `for spline in wall.boundary` to `for spline in wall.boundary.geoms`, and it seems to work.

Then there is an error here:

```
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    G,G_n,G_m = graph_extractor(img_path, out_path)
  File "/home/eason/floorplan/AAG-FP/graph_extractor.py", line 729, in graph_extractor
    G, nodes, edges = build_FPgraph_RAG(output_path, output_path, img_dir)
  File "/home/eason/floorplan/AAG-FP/methods.py", line 404, in build_FPgraph_RAG
    lines.to_file(os.path.join(input_path, filename.split('.')[-2]+"_adjacency.shp"))
  File "/home/eason/anaconda3/envs/floorplan2/lib/python3.7/site-packages/geopandas/geodataframe.py", line 1114, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "/home/eason/anaconda3/envs/floorplan2/lib/python3.7/site-packages/geopandas/io/file.py", line 367, in _to_file
    schema = infer_schema(df)
  File "/home/eason/anaconda3/envs/floorplan2/lib/python3.7/site-packages/geopandas/io/file.py", line 428, in infer_schema
    raise ValueError("Cannot write empty DataFrame to file.")
ValueError: Cannot write empty DataFrame to file.
```

I am not quite sure how to fix it so I just comment it out, line 404 of file `methods.py`.
Then the execution runs towards the end, but I noticed that the output image has lost all adjacency relations.
![image](https://github.com/JanineCHEN/AAG-FP/assets/66631204/7d6735eb-6b32-4f04-a83f-b0db7840ebd7)

**Comment by JanineCHEN** [comment]
Hi @Eason51 , thank you for the detailed feedback, the change of [line 184 of file methods.py](https://github.com/JanineCHEN/AAG-FP/blob/af8a131f3ab4eb85fa5c89c9202daeadb846bb82/methods.py#L184) from `for spline in wall.boundary` to `for spline in wall.boundary.geoms` is indeed necessary, I have updated the scripts accordingly.

Yet I cannot reproduce the loss of adjacency relations error, could you try to downgrade the following packages' version to the specifics listed as follows and try again: `Fiona==1.9.4.post1`, `rasterio==1.2.10`, `Shapely==1.8.5.post1`

**Comment by Eason51** [comment]
Hi, @JanineCHEN, thanks. It worked after the package version update.
